### PR TITLE
2023 AGM Proposal

### PR DESCRIPTION
**Pull request by AndyGaskell**
- Amended clause 23 to automatically remove members after 12 months of non-payment, per issue 1.
- Made one of the directors a membership secretary, per issue 2
- Removed "in the month of April" from the requirement to hold an AGM, per issue 3.
- Removed the requirement to supply the remittance for the first month's subscription at the time of applying for membership, per issue 4.
- Removed all gendered pronouns, per issue 5.
- Amended clause 7 so as not to be in conflict with recently added clause 102.
- Added remote members.
- Fixed line breaks on signatories clause.

### CODE REVIEW

**Comment by AndyGaskell** [comment]
Great looking work from @Nick0o thank you so much for taking time to sort out these changes.

We happy to take this to the AGM as-is? @adventureloop @Hibby

**Comment by AndyGaskell** [comment]
This addresses the issue...
 Remove binary pronouns from articles #5

**Comment by Hibby** [comment]
@AndyGaskell I am unsure about line 171 in the latex file as it defines 35a union st as the anchor location, and the date probably needs to be updated to when it's passed but it can stick as-is for now.

**Comment by Nick0o** [comment]
I'll explain my rationale. I didn't want the centre of the circle to move around if you move the location of the Hacklab again, or for you to need to update the articles of association every time you do move location. I couldn't find any reference to an official "centre" of Aberdeen, Union Street seemed like a good enough centre, so I picked your original address as a sort of nostalgic hat tip to where it all began.

**Comment by ormiret** [comment]
I think the mercat cross would be as close as there is to an official centre of town. Possibly use that? 

It's only a couple hundred metres away from 35A so wouldn't be much difference.

**Comment by AndyGaskell** [comment]
Thanks for the comments, re that bit...

> Remote membership is open to any individual aged 18 or over, who re-
> sides further than 80 kilometres, in a straight line, from 35A Union Street,
> Aberdeen.

...I think either 35A or Mercat cross wound be fine.

Oddly enough, google maps seems indicate if you're going to "Aberdeen",  then you want to go to the crossroad of King St and West North Street / East North Street...
aberdeen

**Comment by AndyGaskell** [comment]
Hi Nick @Nick0o 
I think for the AGM process, we'll have to break this into a bunch of separate merge requests, just so they can be agreed or reject on a change by change basis.  Do you mind if I do that?  I'll keep all your text exactly as it was, really appreciate you putting this merge request together.
Thanks
Andy

**Comment by Nick0o** [comment]
Hi Andy,

Yeah no problem with that. Sounds like a lot of work though, you might want
to wait and see if any of them are rejected before going to the trouble?

Cheers,
Nick

**Comment by AndyGaskell** [comment]
Hi Nick

Ah, it should be ok, you've done the hard work here already really :)

I think the idea is to merge things live during the meeting, as they're agreed.  We'll have to re-generate the PDF from the tex file after the AGM I think, but that'll be fine.

I'll try get it done tomorrow.
Thanks
Andy

**Comment by AndyGaskell** [comment]
This pull request (Thanks @Nick0o 😀) has been split into separate PRs, see...

-  Simplify the membership application process #13 
-  Membership secretary #12 
-  AGM does not have to be in April #11 
-  Remote membership #10 
-  Ending membership if subscription paymants lapse #9 
-  Remove binary pronouns from articles, see issue #5 #8 

So I'll close this one.

**Pull request closed without merging**
